# Site settings
url: "http://umang999.github.io"
title: "{ Umang Parmar }"
description: "Personal website and blog of Umang Parmar, blogging mainly for tech."
keywords: "umang, parmar, developer, personal, blog"
favicon: "/img/favicon.ico"
black-favicon: "/img/favicon.png"
google-tracking-id: "UA-76986233-1"
disqus-shortname: "umangparmar"

# About variables
pages_list:
  About: 'about'
  Career: 'career'
  Contact: 'contact'
me-img: "/img/me.jpg"

##############################
#     Timeline variables     #
##############################
events:
  - image: "/img/career/java.png"
    date: "December 2015"
    description: "Started programming with Java !"
  - image: "/img/career/c.png"
    date: "August 2015"
    description: "My first program with C !"
  - image: "/img/career/unesp.png"
    date: "July 2015 - Until now"
    description: "I'm at University! Information and Communication Technology Studet at DA-IICT. :)"

# First image of the Career timeline
career-img: "/img/career/computer.png"

# Social networks variables (many more available:  flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "facebook"
    url: "https://facebook.com/1.Radhe.357"
  - title: "twitter"
    url: "https://twitter.com/umangjparmar"
  - title: "github"
    url: "https://github.com/Umang999"

404-img: "/img/404.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "info.mk", "vendor"]
gems: [jekyll-paginate]
